backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - label: Programs
    name: programs
    folder: src/data/programs
    create: true
    extension: yml
    fields:
      - { label: Title, name: title, widget: string }
      - label: Start time
        name: startTime
        widget: datetime
        format: YYYY-MM-DD HH:mm
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mmZ
      - label: End time
        name: endTime
        widget: datetime
        format: YYYY-MM-DD HH:mm
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mmZ
      - label: Venue
        name: venue
        widget: select
        options: [IB025, IB028]
      - { label: Abstract, name: abstract, widget: string, required: false }
      - label: Presenter
        name: presenter
        widget: object
        required: false
        fields:
          - { label: Full name, name: fullName, widget: string }
          - { label: Picture source, name: picture, widget: string }
          - label: Organization
            name: organization
            widget: string # TODO: Use 'relation' widget instead
            required: false
          - { label: Region, name: region, widget: string, required: false }
          - { label: Role, name: role, widget: string, required: false }
