backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - label: Programs
    name: programs
    folder: src/data/programs
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Start time, name: startTime, widget: datetime }
      - { label: End time, name: endTime, widget: datetime }
